title: Posts
description: My Personal Stack Problems
author: brightlee
github: https://github.com/brightlee-china
about: 「Stay hungry. Stay foolish.」
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/brightlee-china"

urls:
    - text: About Me
      url: /about/
    - text: Category
      url: /category/jekyll

url: "https://brightlee-china.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
